"""initial migration

Revision ID: edf5b44ff2f7
Revises: 
Create Date: 2021-03-10 10:45:01.923153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edf5b44ff2f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_name'), 'comment', ['name'], unique=True)
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user1', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_user1_username'), 'user1', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user1_username'), table_name='user1')
    op.alter_column('user1', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_table('post_tags')
    op.drop_index(op.f('ix_comment_name'), table_name='comment')
    op.drop_table('comment')
    op.drop_table('tag')
    # ### end Alembic commands ###
